name: Waka Readme

on:
  schedule:
    # Runs every 12 hours
    - cron: '30 */12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: update primary stats section
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"
          COMMIT_EMAIL: "68485672+AnthonyMichaelTDM@users.noreply.github.com" # "41898282+github-actions[bot]@users.noreply.github.com"
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%M %d, %Y %H:%M:%S"
          SHOW_LINES_OF_CODE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "False"
          # IGNORED_REPOS: "" # can be set to "waka-readme-stats, my-first-repo" (just an example) to ignore some repos you don’t want to be counted
          SHOW_LOC_CHART: "False" #DON"T CHANGE THIS
      - name: update LOC
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com" # "68485672+AnthonyMichaelTDM@users.noreply.github.com"
          SHOW_UPDATED_DATE: "False"
          SHOW_LINES_OF_CODE: "True"
          IGNORED_REPOS: "ros2-tutorials, edu-st, my-crispy-arcolinux-configs, my-repo-stats"
          SECTION_NAME: "loc"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          # IGNORED_REPOS: "" # can be set to "waka-readme-stats, my-first-repo" (just an example) to ignore some repos you don’t want to be counted
          SHOW_LOC_CHART: "False" #DON"T CHANGE THIS
          
