name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"
          COMMIT_EMAIL: "68485672+AnthonyMichaelTDM@users.noreply.github.com" # "41898282+github-actions[bot]@users.noreply.github.com"
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%M %d, %Y %H:%M:%S"
          SHOW_LINES_OF_CODE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "False"
          # IGNORED_REPOS: "" # can be set to "waka-readme-stats, my-first-repo" (just an example) to ignore some repos you don’t want to be counted
          SHOW_LOC_CHART: "False" #DON"T CHANGE THIS
          
